# Generated by Django 5.2.7 on 2025-10-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu_De_Donnée',
            fields=[
                ('idJeuDeDonnée', models.AutoField(primary_key=True, serialize=False)),
                ('auteur', models.CharField(blank=True, max_length=100)),
                ('date_création', models.DateTimeField(blank=True, null=True, verbose_name=6)),
                ('email_auteur', models.CharField(blank=True, max_length=100)),
                ('url_licence', models.CharField(blank=True, max_length=200)),
                ('date_création_métadonnées', models.DateTimeField(blank=True, null=True, verbose_name=6)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('nombre_ressources', models.IntegerField(blank=True, null=True)),
                ('nombre_mots_clés', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('idOrganisation', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('statut_dApprobation', models.CharField(blank=True, max_length=45)),
                ('état', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('idGroupe', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, verbose_name=500)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('jeu_de_donnée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnée')),
            ],
        ),
        migrations.CreateModel(
            name='Mot_Clé',
            fields=[
                ('idMotClé', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dAffichage', models.CharField(blank=True, max_length=100)),
                ('mot_clé', models.CharField(blank=True, max_length=100)),
                ('état', models.CharField(blank=True, max_length=45)),
                ('jeu_de_donnée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnée')),
            ],
        ),
        migrations.AddField(
            model_name='jeu_de_donnée',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.organisation'),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('idRessource', models.AutoField(primary_key=True, serialize=False)),
                ('date_création', models.DateTimeField(blank=True, null=True, verbose_name=6)),
                ('description', models.TextField(blank=True, verbose_name=2000)),
                ('format_ressource', models.CharField(blank=True, max_length=50)),
                ('dernière_modification', models.DateTimeField(blank=True, null=True, verbose_name=6)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('type_ressource', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('taille_ressource', models.IntegerField(blank=True, null=True)),
                ('jeu_de_donnée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnée')),
            ],
        ),
    ]
