# Generated by Django 5.2.7 on 2025-10-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMoisson',
            fields=[
                ('idConfigMoisson', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('DonneesQuebec', 'https://www.donneesquebec.ca/recherche/api/3/action/package_search'), ('CanWIN', 'https://canwin-datahub.ad.umanitoba.ca/data/api/3/action/package_search'), ('OpenGouv', 'https://open.canada.ca/data/api/action/package_search'), ('Borealis', 'https://borealisdata.ca/api/search')], max_length=500)),
                ('filtres', models.CharField(blank=True, max_length=300)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('dernier_lancement', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de Moissonnage',
                'verbose_name_plural': 'Configurations de Moissonnage',
                'db_table': 'config_moisson',
            },
        ),
        migrations.CreateModel(
            name='Jeu_De_Donnee',
            fields=[
                ('idJeuDeDonnee', models.AutoField(primary_key=True, serialize=False, verbose_name='idJeuDeDonnée')),
                ('auteur', models.CharField(blank=True, max_length=500, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True, verbose_name='date_de_création')),
                ('email_auteur', models.CharField(blank=True, max_length=500, null=True)),
                ('url_licence', models.CharField(blank=True, max_length=500, null=True)),
                ('date_creation_metadonnees', models.DateTimeField(blank=True, null=True, verbose_name='date_de_création_des_métadonnées')),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_ressources', models.IntegerField(blank=True, null=True)),
                ('nombre_mots_cles', models.IntegerField(blank=True, null=True, verbose_name='nombre_de_mots_clés')),
            ],
            options={
                'verbose_name': 'Jeu De Donnée',
                'verbose_name_plural': 'Jeux De Données',
                'db_table': 'jeu_de_donnee',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('idOrganisation', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('titre', models.CharField(blank=True, max_length=500, null=True)),
                ('statut_dApprobation', models.CharField(blank=True, max_length=45, null=True)),
                ('etat', models.CharField(blank=True, max_length=45, null=True, verbose_name='état')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organisation',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('idGroupe', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name=1000)),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('titre', models.CharField(blank=True, max_length=500, null=True)),
                ('jeu_de_donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnee')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Mot_Cle',
            fields=[
                ('idMotCle', models.AutoField(primary_key=True, serialize=False, verbose_name='idMotClé')),
                ('nom_dAffichage', models.CharField(blank=True, max_length=100, null=True)),
                ('mot_cle', models.CharField(blank=True, max_length=100, null=True, verbose_name='mot-clé')),
                ('etat', models.CharField(blank=True, max_length=45, null=True, verbose_name='état')),
                ('jeu_de_donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnee', verbose_name='jeu_de_donnée')),
            ],
            options={
                'verbose_name': 'Mot-Clé',
                'verbose_name_plural': 'Mots-Clés',
                'db_table': 'mot_cle',
            },
        ),
        migrations.AddField(
            model_name='jeu_de_donnee',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.organisation'),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('idRessource', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(blank=True, null=True, verbose_name='date de création')),
                ('description', models.TextField(blank=True, null=True, verbose_name=2000)),
                ('format_ressource', models.CharField(blank=True, max_length=50)),
                ('derniere_modification', models.DateTimeField(blank=True, null=True, verbose_name='date de dernière modification')),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('type_ressource', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('taille_ressource', models.IntegerField(blank=True, null=True)),
                ('jeu_de_donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnee', verbose_name='jeu_de_donnée')),
            ],
        ),
    ]
