# Generated by Django 5.2.7 on 2025-10-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='group',
            name='nom',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='titre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='auteur',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='email_auteur',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='nom',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='url_licence',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='nom',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='titre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='nom',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
