# Generated by Django 5.2.7 on 2025-11-10 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu_de_donnee',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnee',
            name='date_creation_metadonnees',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de création des métadonnées'),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnee',
            name='nombre_mots_cles',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de mots clés'),
        ),
        migrations.AlterField(
            model_name='mot_cle',
            name='jeu_de_donnee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnee', verbose_name='jeu de donnée'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='jeu_de_donnee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.jeu_de_donnee', verbose_name='jeu de donnée'),
        ),
        migrations.CreateModel(
            name='LogMoissonage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commence', models.DateTimeField(auto_now_add=True, verbose_name='Commencé à')),
                ('complete', models.DateTimeField(blank=True, null=True, verbose_name='Completé à')),
                ('statut', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('error', 'Erreur')], max_length=20)),
                ('records_harvested', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueDonnées.configmoisson')),
            ],
            options={
                'ordering': ['-commence'],
            },
        ),
    ]
