# Generated by Django 5.2.7 on 2025-11-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0002_alter_jeu_de_donnee_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu_de_donnee',
            name='nombre_ressources',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de ressources'),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnee',
            name='url_licence',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pour le réferencement'),
        ),
    ]
