# Generated by Django 5.2.7 on 2025-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0002_alter_group_description_alter_group_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMoisson',
            fields=[
                ('idConfigMoisson', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('DonneesQuebec', 'https://www.donneesquebec.ca/recherche/api/3/action/package_search'), ('CanWIN', 'https://canwin-datahub.ad.umanitoba.ca/data/api/3/action/package_search'), ('OpenGouv', 'https://open.canada.ca/data/api/action/package_search'), ('Borealis', 'https://borealisdata.ca/api/search')], max_length=500)),
                ('filtres', models.CharField(blank=True, max_length=300)),
                ('dernier_lancement', models.DateTimeField(auto_now=True, verbose_name=6)),
            ],
        ),
    ]
