# Generated by Django 5.2.7 on 2025-11-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0003_alter_jeu_de_donnee_nombre_ressources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmoissonage',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name="Message d'érreur"),
        ),
        migrations.AlterField(
            model_name='logmoissonage',
            name='records_harvested',
            field=models.IntegerField(default=0, verbose_name='Données moissonnées'),
        ),
    ]
