# Generated by Django 5.2.7 on 2025-10-30 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0003_configmoisson'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmoisson',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=6),
            preserve_default=False,
        ),
    ]
