# Generated by Django 5.2.7 on 2025-10-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0004_configmoisson_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmoisson',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='configmoisson',
            name='dernier_lancement',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='date_création',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='date_création_métadonnées',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='dernière_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
