# Generated by Django 5.2.7 on 2025-11-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0004_alter_logmoissonage_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmoisson',
            name='source',
            field=models.CharField(choices=[('https://www.donneesquebec.ca/recherche/api/3/action/package_search', 'DonneesQuebec'), ('https://canwin-datahub.ad.umanitoba.ca/data/api/3/action/package_search', 'CanWIN'), ('https://open.canada.ca/data/api/action/package_search', 'OpenGouv'), ('https://borealisdata.ca/api/search', 'Borealis')], max_length=500),
        ),
    ]
