# Generated by Django 5.2.7 on 2025-11-13 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0005_alter_configmoisson_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmoissonage',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogueDonnées.configmoisson'),
        ),
    ]
