# Generated by Django 5.2.7 on 2025-10-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0005_alter_configmoisson_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='auteur',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
