# Generated by Django 5.2.7 on 2025-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0006_alter_logmoissonage_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmoissonage',
            name='statut',
            field=models.CharField(choices=[('running', 'En cours'), ('Succès', 'success'), ('Erreur', 'error')], max_length=20),
        ),
    ]
