# Generated by Django 5.2.7 on 2025-10-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0006_alter_jeu_de_donnée_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='group',
            name='nom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='titre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='email_auteur',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='nom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jeu_de_donnée',
            name='url_licence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mot_clé',
            name='mot_clé',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mot_clé',
            name='nom_dAffichage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mot_clé',
            name='état',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='nom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='statut_dApprobation',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='titre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='état',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=2000),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='nom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type_ressource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
