# Generated by Django 5.2.7 on 2025-10-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0007_alter_group_description_alter_group_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='date_création',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
