# Generated by Django 5.2.7 on 2025-10-31 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0008_alter_ressource_date_création'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='jeu_de_donnée',
            new_name='jeu_de_donnee',
        ),
        migrations.RenameField(
            model_name='jeu_de_donnée',
            old_name='date_création_métadonnées',
            new_name='date_creation_metadonnees',
        ),
        migrations.RenameField(
            model_name='jeu_de_donnée',
            old_name='idJeuDeDonnée',
            new_name='idJeuDeDonnee',
        ),
        migrations.RenameField(
            model_name='jeu_de_donnée',
            old_name='nombre_mots_clés',
            new_name='nombre_mots_cles',
        ),
        migrations.RenameField(
            model_name='mot_clé',
            old_name='idMotClé',
            new_name='idMotCle',
        ),
        migrations.RenameField(
            model_name='mot_clé',
            old_name='jeu_de_donnée',
            new_name='jeu_de_donnee',
        ),
        migrations.RenameField(
            model_name='ressource',
            old_name='date_création',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='ressource',
            old_name='jeu_de_donnée',
            new_name='jeu_de_donnee',
        ),
    ]
