# Generated by Django 5.2.7 on 2025-10-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0009_rename_jeu_de_donnée_group_jeu_de_donnee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeu_de_donnée',
            old_name='date_création',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='mot_clé',
            old_name='mot_clé',
            new_name='mot_cle',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='état',
            new_name='etat',
        ),
        migrations.RenameField(
            model_name='ressource',
            old_name='dernière_modification',
            new_name='derniere_modification',
        ),
    ]
