# Generated by Django 5.2.7 on 2025-10-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueDonnées', '0010_rename_date_création_jeu_de_donnée_date_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mot_clé',
            old_name='état',
            new_name='etat',
        ),
    ]
